// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm build-cf-types`

// biome-ignore lint/suspicious/noEmptyInterface: <explanation>
interface Env {}
